//
// Created by Jose on 11/4/2026.
//

#ifndef PROYECTOL_PROGRAMACIONLL_ARCHIVOINVALIDOEXCEPTION_H
#define PROYECTOL_PROGRAMACIONLL_ARCHIVOINVALIDOEXCEPTION_H


class ArchivoInvalidoException {
};


#endif //PROYECTOL_PROGRAMACIONLL_ARCHIVOINVALIDOEXCEPTION_H