//
// Created by Jose on 11/4/2026.
//

#ifndef PROYECTOL_PROGRAMACIONLL_FORMATOINVALIDOEXCEPTION_H
#define PROYECTOL_PROGRAMACIONLL_FORMATOINVALIDOEXCEPTION_H


class FormatoInvalidoException {
};


#endif //PROYECTOL_PROGRAMACIONLL_FORMATOINVALIDOEXCEPTION_H