//
// Created by Jose on 11/4/2026.
//

#ifndef PROYECTOL_PROGRAMACIONLL_GENERADORREPORTES_H
#define PROYECTOL_PROGRAMACIONLL_GENERADORREPORTES_H


class GeneradorReportes {
};


#endif //PROYECTOL_PROGRAMACIONLL_GENERADORREPORTES_H