//
// Created by Jose on 11/4/2026.
//

#ifndef PROYECTOL_PROGRAMACIONLL_OPERACIONINCONSISTENTEEXCEPTION_H
#define PROYECTOL_PROGRAMACIONLL_OPERACIONINCONSISTENTEEXCEPTION_H


class OperacionInconsistenteException {
};


#endif //PROYECTOL_PROGRAMACIONLL_OPERACIONINCONSISTENTEEXCEPTION_H