//
// Created by Jose on 11/4/2026.
//

#ifndef PROYECTOL_PROGRAMACIONLL_ORDENAMIENTODIARIO_H
#define PROYECTOL_PROGRAMACIONLL_ORDENAMIENTODIARIO_H


class OrdenamientoDiario {
};


#endif //PROYECTOL_PROGRAMACIONLL_ORDENAMIENTODIARIO_H